FROM node:latest

RUN git clone https://github.com/niklasvh/html2canvas.git

WORKDIR html2canvas

RUN apt-get update && apt-get install -y apt-transport-https

RUN apt-get install npm

RUN npm install

RUN npm run build
